.PHONY:all
all:TcpClient TcpServer

TcpClient:TcpClient.cc
	g++ -o TcpClient TcpClient.cc
TcpServer:TcpServer.cc
	g++ -o TcpServer TcpServer.cc

.PHONY:clean
clean:
	rm -f TcpClient TcpServer









